# Generated by Django 3.1.4 on 2020-12-11 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leetBlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='content',
        ),
    ]
